### PR TITLE
add osx_arm64 support

### PR DESCRIPTION
**Pull request by matthiasdiener**
Based on #5

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
I think this is picking up a completion file from the docker image, which fail for yum completions since yum is not installed.

**Comment by matthiasdiener** [comment]
This is ready for review @conda-forge/bash-completion

**Review by tartansandal — APPROVED** [review]
Excellent! Thanks for tracking down and resolving the the yum issue @matthiasdiener :smile:

**Comment by matthiasdiener** [comment]
> Excellent! Thanks for tracking down and resolving the the yum issue @matthiasdiener 😄

Thank you @tartansandal ! Please feel free to merge when it's ready, I don't have permission yet. I added myself as maintainer and will work on ppc64le/aarch64 next.

**Pull request merged**
